---
title: "ZJStatistics #1 Nov 2020"
subtitle: "作者：顶碗人在这里"
output: 
  html_notebook:
    includes:
      before_body: style.html
    number_sections: true
    code_folding: hide
---
# 环境
```{r message=FALSE, warning=FALSE}
library(tidyverse)
setwd("D:/A-SOUL/ZJStatistics/ZJStatistics/analysis")
```

# 数据读入
```{r}
df <- read.csv("../data/stream_video.csv",header=T)
```
# 数据导入
stream_video.csv在创建时为保证读入时正确识别每列的变量类型，插入了一行无用数据，该数据将被去除  

## 2020-11-23 乐华娱乐年度企划A-SOUL来啦！敬请期待！~
A-SOUL在b站上的第一个视频，内容为五人黑影舞蹈，记为五位成员表演1支舞蹈。
```{r}
df <- df %>% add_row(time="2020-11-23",
                      title="B站2020-11-23乐华娱乐年度企划A-SOUL来啦！敬请期待！~",
                      type="bv",
                      length=36,
                      member="ABCDE",
                      nSongA=0,lenSongA=0,nDanceA=1,lenDanceA=36,
                      nSongB=0,lenSongB=0,nDanceB=1,lenDanceB=36,
                      nSongC=0,lenSongC=0,nDanceC=1,lenDanceC=36,
                      nSongD=0,lenSongD=0,nDanceD=1,lenDanceD=36,
                      nSongE=0,lenSongE=0,nDanceE=1,lenDanceE=36,
                      source="X",
                      link="www.bilibili.com/video/BV1my4y167r7",
                      other="",
                      creator='uid:3510653')
df <- df[-1,] #去除初始数据
```

## 2020-11-27 【3D模型展示】A-SOUL大家的常服~
A-SOUL在b站上的第二个视频，虽为成员展示，但成员均有动作，因此记为五人参与拍摄了
的原创视频（还有阿草）。
```{r}
df <- df %>% add_row(time="2020-11-27",
                      title="【3D模型展示】A-SOUL大家的常服~",
                      type="bv",
                      length=28,
                      member="XABCDE",
                      nSongA=0,lenSongA=0,nDanceA=0,lenDanceA=0,
                      nSongB=0,lenSongB=0,nDanceB=0,lenDanceB=0,
                      nSongC=0,lenSongC=0,nDanceC=0,lenDanceC=0,
                      nSongD=0,lenSongD=0,nDanceD=0,lenDanceD=0,
                      nSongE=0,lenSongE=0,nDanceE=0,lenDanceE=0,
                      source="X",
                      link="www.bilibili.com/video/BV1ja4y1W7jp",
                      other="",
                      creator='uid:3510653')
```
11月份全部的数据收集完毕，写入文档。
```{r}
write.csv(df,"../data/stream_video.csv",row.names=FALSE)
```

# 数据分析

